language : node_js
node_js :
 - 10
install:
 - yarn install
script:
  - docker build -t $DOCKER_USER/persion-do-list:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/persion-do-list:latest
  - docker tag $DOCKER_USER/persion-do-list:latest $DOCKER_USER/persion-do-list:`git describe --abbrev=0 --tags`
  - docker push $DOCKER_USER/persion-do-list:`git describe --abbrev=0 --tags`