language : node_js
node_js :
 - 10
git:
  depth: false
env:
  global:
    - PRO_TAG= $(git describe --abbrev=0 --tags)
install:
 - yarn install
script:
  - docker build -t $DOCKER_USER/persion-do-list:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/persion-do-list:latest
  - docker tag $DOCKER_USER/persion-do-list:latest $DOCKER_USER/persion-do-list:v${PRO_TAG} 
  - docker push $DOCKER_USER/persion-do-list:v${PRO_TAG}